image: Visual Studio 2017 Preview
configuration: Release

init:
  - git config --global core.autocrlf input

environment:
  # Set the DOTNET_SKIP_FIRST_TIME_EXPERIENCE environment variable to stop wasting time caching packages
  DOTNET_SKIP_FIRST_TIME_EXPERIENCE: true
  # Disable sending usage data to Microsoft
  DOTNET_CLI_TELEMETRY_OPTOUT: true

install:
  - cmd: curl -O https://download.microsoft.com/download/0/F/D/0FD852A4-7EA1-4E2A-983A-0484AC19B92C/dotnet-sdk-2.0.0-win-x64.exe
  - cmd: dotnet-sdk-2.0.0-win-x64.exe /install /quiet /norestart /log install.log 


build_script:
- ps: .\build.ps1 -BuildNumber "$env:APPVEYOR_BUILD_NUMBER" -RunTests $false

test: off

artifacts:
- path: .\.nupkgs\*.nupkg

deploy:
- provider: NuGet
  api_key:
    secure: eaiytjZ8451bGqdim49VhzfsYNDviMmEm/lMbc34oqmznMUEb0BW/9/yFckWyzf1
  on:
    branch: master
